In [83]:
# Using Classification to predict the review by amazon customers 

In [84]:
import numpy as np
import pandas as pd


In [85]:
data = pd.read_csv("C:/Users/Georage/Downloads/archive (1)/beginner_datasets/amazon.csv")
data.head()

reviewText  Positive
0  This is a one of the best apps acording to a b...         1
1  This is a pretty good version of the game for ...         1
2  this is a really cool game. there are a bunch ...         1
3  This is a silly game and can be frustrating, b...         1
4  This is a terrific game on any pad. Hrs of fun...         1

In [86]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   reviewText  20000 non-null  object
 1   Positive    20000 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 312.6+ KB


In [87]:
data.isna().sum()

reviewText    0
Positive      0
dtype: int64

In [88]:
data.describe()

Positive
count  20000.000000
mean       0.761650
std        0.426085
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000

In [89]:
from sklearn.preprocessing import LabelEncoder
print('Categorical Columns: ')
for col in data.columns:
    if data[col].dtype == 'object':
        print(str(col))
        labelencoder = LabelEncoder()
        label = labelencoder.fit(data[col])
        data[col] = label.transform(data[col].astype(str))

Categorical Columns: 
reviewText


In [90]:
data.head()

reviewText  Positive
0       13855         1
1       13863         1
2       19250         1
3       13901         1
4       13923         1

In [91]:
X = data.iloc[: , 0].values
y = data.iloc[:, 1].values

In [92]:
X = np.array(X).reshape(-1,1)
y = np.array(y).reshape(-1,1)

In [93]:
from sklearn.model_selection import train_test_split
X_train ,X_test,y_train , y_test = train_test_split(X,y, test_size = 0.2 , random_state = 0)

In [94]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()
lg.fit(X_train , y_train)

C:\Users\Georage\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [95]:
y_pred = lg.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [96]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       933
           1       0.77      1.00      0.87      3067

    accuracy                           0.77      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.59      0.77      0.67      4000



C:\Users\Georage\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Georage\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Georage\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [97]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[   0  933]
 [   0 3067]]


In [98]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

0.76675


In [99]:
from sklearn.tree import DecisionTreeClassifier
d_tree = DecisionTreeClassifier()
d_tree.fit(X_train , y_train)

DecisionTreeClassifier()

In [100]:
y_pred = d_tree.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [101]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.46      0.46      0.46       933
           1       0.84      0.84      0.84      3067

    accuracy                           0.75      4000
   macro avg       0.65      0.65      0.65      4000
weighted avg       0.75      0.75      0.75      4000



In [102]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 427  506]
 [ 501 2566]]


In [103]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

0.74825


In [104]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

C:\Users\Georage\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [105]:
y_pred = knn.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [106]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.56      0.40      0.47       933
           1       0.83      0.91      0.87      3067

    accuracy                           0.79      4000
   macro avg       0.70      0.65      0.67      4000
weighted avg       0.77      0.79      0.77      4000



In [107]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 370  563]
 [ 286 2781]]


In [108]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

0.78775


In [109]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier()
forest.fit(X_train , y_train)

C:\Users\Georage\AppData\Local\Temp\ipykernel_10320\1234600124.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest.fit(X_train , y_train)


RandomForestClassifier()

In [110]:
y_pred = forest.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [111]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.46      0.46      0.46       933
           1       0.84      0.84      0.84      3067

    accuracy                           0.75      4000
   macro avg       0.65      0.65      0.65      4000
weighted avg       0.75      0.75      0.75      4000



In [112]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

[[ 427  506]
 [ 500 2567]]
0.7485


In [113]:
from sklearn.svm import SVC
sp = SVC()
sp.fit(X_train , y_train)

C:\Users\Georage\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [114]:
y_pred = sp.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [115]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))
     
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       933
           1       0.77      1.00      0.87      3067

    accuracy                           0.77      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.59      0.77      0.67      4000

[[   0  933]
 [   0 3067]]
0.76675


C:\Users\Georage\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Georage\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Georage\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
